name: CD

on:
  push:
    branches:
      - master

jobs:
  helpers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Current Time
        id: current-time
        run: echo "::set-output name=curr-time::$(date +%s)"
      - name: Get Current Formatted Time
        id: current-formatted-time
        run: echo "::set-output name=curr-ftime::$(date -d '@${{ steps.current-time.outputs.curr-time }}')"
      - name: Get Commit SHA
        id: git-sha
        run: echo "::set-output name=git-sha::$(git rev-parse --short HEAD)"
      - name: Get Release Name
        id: release-name
        run: echo "::set-output name=pkg-name::$(cat package.json | jq -r '.name')"
      - name: Get Release Description
        id: release-description
        run: echo "::set-output name=pkg-desc::$(cat package.json | jq -r '.description')"
      - name: Get Release Version
        id: release-version
        run: echo "::set-output name=pkg-ver::$(cat package.json | jq -r '.version')"
      - name: Wait for test pipeline to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: master
          check-name: CI
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
    outputs:
      git-sha: ${{ steps.git-sha.outputs.git-sha }}
      curr-time: ${{ steps.current-time.outputs.curr-time }}
      curr-ftime: ${{ steps.current-formatted-time.outputs.curr-ftime }}
      pkg-name: ${{ steps.release-name.outputs.pkg-name }}
      pkg-desc: ${{ steps.release-description.outputs.pkg-desc }}
      pkg-ver: ${{ steps.release-version.outputs.pkg-ver }}

  build-linux:
    needs: helpers
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Prepare Repo
        run: sudo dpkg --add-architecture i386 && sudo apt-get update
      - name: Build App for Linux
        run: yarn build --linux
      - name: Upload Linux AppImage & Snap Client
        uses: actions/upload-artifact@v2
        with:
          name: ${{ needs.helpers.outputs.pkg-name }}-${{ needs.helpers.outputs.pkg-ver }}-lin
          path: |
            dist/${{ needs.helpers.outputs.pkg-desc }}-${{ needs.helpers.outputs.pkg-ver }}.AppImage
            dist/${{ needs.helpers.outputs.pkg-name }}_${{ needs.helpers.outputs.pkg-ver }}_amd64.snap

  build-macos:
    needs: helpers
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build App for macOS
        run: yarn build --mac
      - name: Upload macOS DMG Client
        uses: actions/upload-artifact@v2
        with:
          name: ${{ needs.helpers.outputs.pkg-name }}-${{ needs.helpers.outputs.pkg-ver }}-mac
          path: dist/${{ needs.helpers.outputs.pkg-desc }}-${{ needs.helpers.outputs.pkg-ver }}.dmg

  build-windows:
    needs: helpers
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install
      - name: Build App for Windows
        run: yarn build --win
      - name: Upload Windows EXE Client
        uses: actions/upload-artifact@v2
        with:
          name: ${{ needs.helpers.outputs.pkg-name }}-${{ needs.helpers.outputs.pkg-ver }}-win
          path: dist/${{ needs.helpers.outputs.pkg-desc }} Setup ${{ needs.helpers.outputs.pkg-ver }}.exe

  release:
    needs: [helpers, build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux AppImage & Snap Client
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.helpers.outputs.pkg-name }}-${{ needs.helpers.outputs.pkg-ver }}-lin
      - name: Download Windows EXE Client
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.helpers.outputs.pkg-name }}-${{ needs.helpers.outputs.pkg-ver }}-win
      - name: Download macOS DMG Client
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.helpers.outputs.pkg-name }}-${{ needs.helpers.outputs.pkg-ver }}-mac
      - name: Release Packages
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.helpers.outputs.git-sha }}
          name: ${{ needs.helpers.outputs.pkg-ver }}-${{ needs.helpers.outputs.curr-time}}-${{ needs.helpers.outputs.git-sha }}
          prerelease: true
          body: |
            ${{ needs.helpers.pkg-name }} auto built for ${{ needs.helpers.outputs.git-sha }} on ${{ needs.helpers.outputs.curr-ftime }}
          files: |
            ${{ needs.helpers.outputs.pkg-desc }}-${{ needs.helpers.outputs.pkg-ver }}.AppImage
            ${{ needs.helpers.outputs.pkg-name }}_${{ needs.helpers.outputs.pkg-ver }}_amd64.snap
            ${{ needs.helpers.outputs.pkg-desc }} Setup ${{ needs.helpers.outputs.pkg-ver }}.exe
            ${{ needs.helpers.outputs.pkg-desc }}-${{ needs.helpers.outputs.pkg-ver }}.dmg
